version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./frontend
    ports:
      # - "3000:3000"
      - "3000:5173"
      # - "3000:80"
    command: npm run dev -- --host 0.0.0.0 --port 5173 
    environment:
    - HOST=0.0.0.0

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3001"
    